---
- name: "add attributes"
  lineinfile:
    path: "{{ OS.radius.dirs.conf }}/dictionary"
    line: "{{ item }}"
  with_items:
    - "ATTRIBUTE DHCP-Router-IP-Address 241 ipaddr"
    - "ATTRIBUTE DHCP-Mask 242 integer"
    - "ATTRIBUTE L4-Redirect 243 integer"
    - "ATTRIBUTE L4-Redirect-ipset 244 string"
    - "ATTRIBUTE DHCP-Option82 245 octets"
    - "#ATTRIBUTE DHCP-Agent-Circuit-Id 1 octets"
    - "#ATTRIBUTE DHCP-Agent-Remote-Id 2 octets"
    - "ATTRIBUTE AccelRemoteId 246 octets"
    - "ATTRIBUTE AccelCircuitId 247 octets"
    - "#ATTRIBUTE DHCP-Attr-272 272 ipaddr"