---
- name: "set root password"
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ hostvars[inventory_hostname].root_passwd }}"
    login_unix_socket: "{{ OS.database.percona.socket }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"