---
- name: "add dependencies for PHP"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_distribution == "Debian"

- name: "add ondrej sury's apt key"
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_distribution == "Debian"

- name: "add ondrej sury's repo"
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  when: ansible_distribution == "Debian"

- name: "update apt caches after repo is added"
  apt: update_cache=true
  when: php_ondrej_debian_repo.changed and (ansible_distribution == "Debian")
