---
- include_tasks: add_sury_repo.yml
  when: ansible_os_family | lower == 'debian'

- include_tasks: update_python-httplib2.yml
  when: 
     - ansible_os_family | lower == 'debian'
     - ansible_distribution_major_version == "8"

- include_tasks: add_epel_remi_repo.yml
  when: ansible_os_family | lower == 'redhat'

- include_tasks: "install_{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}.yml"
- include_tasks: disable_modules.yml